### ISSUE TITLE
Add 'medicare_status_code' terminology dataset

### ISSUE THREAD

**Issue by cocozuloaga** [tuva-health/terminology#11]
Decide what the accepted normalized values for the 'medicare_status_code' field are in the Tuva Data Model and create a terminology file with those values.

**Comment by tuvaforrest** [comment]
we will have one terminology set for medicare status code and description.  currently here https://github.com/tuva-health/terminology/blob/main/terminology/medicare_status_code.csv but I will change it to "medicare_status" in the next pr.  closing this issue as its tracked separately (in an issue for medicare_status_code)
