### ISSUE TITLE
Update Bill Type Code to Include Frequency Letter

### ISSUE THREAD

**Issue by thutuva** [tuva-health/terminology#16]
Please update the bill_type.csv file to include bill type codes that end with a letter value.  For example, bill type code 11H is a valid code and it is present in the Medicare SAF data.  However code 11H is not in the seed file so data quality failures are being incorrectly produced.  See [this page from ResDAC](https://resdac.org/cms-data/variables/bill-type-code) for additional information.

Tagging @sarah-tuva so she's aware for data profiling.

**Comment by tuvaforrest** [comment]
Confirming prof bill type codes with letters are now present in current iteration of main branch.
